config:
  providers:
    - name: provider1
      url: https://provider1.com/v1/api/account/validate
    - name: provider2
      url: https://provider2.com/v2/api/account/validate
    - name: provider3
      url: https://provider3.com/v1/api/account/validate
    - name: provider4
      url: https://provider4.com/v2/api/account/validate
    - name: provider5
      url: https://provider1.com/v1/api/account/validate
    - name: provider6
      url: https://provider2.com/v2/api/account/validate
    - name: provider7
      url: https://provider3.com/v1/api/account/validate
    - name: provider8
      url: https://provider4.com/v2/api/account/validate
    - name: provider9
      url: https://provider1.com/v1/api/account/validate
    - name: provider10
      url: https://provider2.com/v2/api/account/validate
    - name: provider11
      url: https://provider3.com/v1/api/account/validate
    - name: provider12
      url: https://provider4.com/v2/api/account/validate